#!/usr/bin/php
<?php
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.


//patch php.ini
$php_ini = getenv('OPENSHIFT_PRIMARY_CARTRIDGE_DIR').'/configuration/etc/php.ini';
if ( file_exists($php_ini) )
{
	$content= file_get_contents($php_ini);
	if ( strpos($content,'xdebug.remote_autostart') === false ) {
		$content .= "xdebug.remote_autostart=0\nxdebug.remote_enable=0\nxdebug.max_nesting_level=500";
		file_put_contents($php_ini, $content);
	}
}
?>
